### ISSUE TITLE
Error lefff-3.4.mlex not found

### ISSUE THREAD

**Issue by alexandreraufast** [ClaudeCoulombe/FrenchLefffLemmatizer#1]
Error while testing the package on Windows 10
(Installed through pip3)

```>>> lemmatizer = FrenchLefffLemmatizer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Tensorflow\Anaconda3\lib\site-packages\french_lefff_lemmatizer\french_lefff_lemmatizer.py", line 61, in __init__
    with open(self.LEFFF_FILE_STORAGE, encoding='utf-8') as lefff_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\Anaconda3\\lib\\site-packages\\french_lefff_lemmatizer/data/lefff-3.4.mlex'```

I think there is an error in the path creation.

**Comment by DataTriny** [comment]
Hello,

I encountered the same issue on Debian. I was using a `requirements.txt` file to install my dependencies, and the line corresponding to `FrenchLefffLemmatizer` was wrong, making `pip` download something else from `files.pythonhosted.org`.

@alexandreraufast  make sure to follow installation instructions, and check that a `git clone` is performed when installing.

If you are also using a `requirements.txt` file to store your dependencies, put this line inside it (no package name required):

```
git+git://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
```

Regards.
